baseURL = "/"
title = "lil-bioinf"
copyright = "Copyright © 2019, Gabriella Morgenshtern & Cait Harrigan"
languageCode = "en-US"
theme = "indigo"
paginate = 3
publishDir = "public"

[social]
  github = "https://github.com/harrig12/lil-bioinf"

[params]
  Author = "Author Name"
  Description = "Workshop - R for Bioinformatics"
  Subtitle = "An introductory workshop to R for bioinformatics"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  ShowDatesOnPosts = false
  ShowDatesOnPages = true
  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
  GitHubUser = "harrig12/lil-bioinf"
